Add events
alef-garrido/react-spa-math-magicians pull request #3
Opened 2022-02-10 05:53 UTC by alef-garrido

- Added logic files for calculator component
- Split Component, adding Display Component
- Lift state up from display and calculator components to parent component(App)
- Added event handlers

2022-02-10 21:42 UTC, andersonlebon requested changes
### Hi @alef-garrido 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Nice use of lifecycle methods :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 21:42 UTC, andersonlebon commented on src/App.js
> +
- [ ] Nice job :clap: on implementing these events, however when I click on `0` then click on any other number I can see that the following number is coming with a `0` in front like `0222`, Kindly let's go ahead and fix I. check the screenshot below :point_down: 
![image](https://user-images.githubusercontent.com/65068771/153496554-5b75f3f9-d962-4527-94dc-b75237af871d.png)

2022-02-10 21:42 UTC, andersonlebon commented on src/App.css
>  }
## [OPTIONAL]
- [ ] Also for accessibly reasons Kindly make sure that when any button hovered the text inside should be clear, currently when I hover any button the text inside disappears. check the screenshot below :point_down: 
![image](https://user-images.githubusercontent.com/65068771/153496554-5b75f3f9-d962-4527-94dc-b75237af871d.png)

2022-02-10 21:42 UTC, andersonlebon commented on src/App.js
> +
## [OPTIONAL]
- [ ] Nice use of click event however in new react syntax you can just use array function instead of binding your function, check the example below :point_down: 

#### Your code 
````jsx
class App extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = this.handleChange.bind(this);
    this.handleClick = this.handleClick.bind(this);

    this.state = {
      total: null,
      next: null,
      operation: null,
    };
  }

  handleChange(e) {
    const input = calculate(this.state, e.target.value);
    this.setState(input);
  }

  handleClick(e) {
    const calc = calculate(this.state, e.target.name);
    this.setState(calc);
  }
render(){........................................}
}
````
#### Using the arraw function syntax
````jsx
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      total: null,
      next: null,
      operation: null,
    };
  }

  const handleChange = (e) => {
    const input = calculate(this.state, e.target.value);
    this.setState(input);
  }

 const handleClick = (e) => {
    const calc = calculate(this.state, e.target.name);
    this.setState(calc);
  }
render(){........................................}
}
````

2022-02-10 21:42 UTC, andersonlebon commented on src/App.js
> +import calculate from './logic/calculate';
- [ ] As one of the requirements says yous should import the `Calculate` component in `calculator.js` rather than in `App.js` this will make your structure clear and easy to understand because all the logic concerning calculation is going to be inside the `calculator.js` file your `App.js` file should be only responsible for rendering the `Calculator` component.

2022-02-10 23:00 UTC, alef-garrido commented on src/App.css
>  }
This was fixed on my second to last commit, but thank you for noticing!

2022-02-10 23:31 UTC, alef-garrido commented on src/App.js
> +
I didn't notice that! However i believe this is an edge case that's not considered in the "calculate" file we were provided. I checked some projects and they all seem to have the same problem. Have you tried to solve it? This seems beyond the requirements. I

2022-02-10 23:35 UTC, alef-garrido commented on src/App.js
> +import calculate from './logic/calculate';
Hello again, and thank you for your attention to detail. I understand that that's a requirement, but in order to experiment with "liftstate up" i moved the handlers to the parent. Is not optimal or best practice but implementing lift state up was also a requirement.

2022-02-10 23:49 UTC, andersonlebon commented on src/App.js
> +
hello @alef-garrido,

2022-02-10 23:51 UTC, andersonlebon commented on src/App.js
> +
I can see it is challenging but I have found a way you can solve it.

2022-02-11 00:02 UTC, andersonlebon commented on src/logic/calculate.js
> +      if (obj.next) {
- [ ] here also use this condition :point_down: 
```js
      if (obj.next && obj.next !== '0') {
         .........................................
      }

```

2022-02-11 00:22 UTC, andersonlebon commented on src/App.js
> +import calculate from './logic/calculate';
Okay, I understand, however, to keep your code clear and easy to understand your `App.js` should only be responsible for rendering routes and the calculated for now. Lifting up the state doesn't only mean that your `App.js` should be the only one having the state. Even your calculator component might have the state, the idea is as long as you have one single source of truth (state) your state is left-up. You can read more [here](https://reactjs.org/docs/lifting-state-up.html)

2022-02-11 01:48 UTC, alef-garrido commented on src/logic/calculate.js
> +    if (obj.next) {
This is what i've been trying but this generates another issue, when you try to use an amount starting with 0, it will override the 0. Entering 0.2 will display 2.

2022-02-11 01:50 UTC, alef-garrido commented on src/logic/calculate.js
> +      if (obj.next) {
Yup, that was my first instinct too. but it mess with the logic in a way that prevents the user to enter amounts with a dot.

2022-02-11 03:22 UTC, alef-garrido commented on src/logic/calculate.js
> +    if (obj.next) {
That's awesome, it's only a minor change.

2022-02-11 03:32 UTC, alef-garrido commented on src/logic/calculate.js
> +      if (obj.next) {
Thank you for replying to the comments I made.  Changes have been done!

2022-02-11 04:36 UTC, Meltrust approved these changes
Hi @alef-garrido,

### To highlight:

- Thank you for implementing the changes requested by the previous reviewer✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 05:10 UTC, merged

2022-02-11 06:00 UTC, andersonlebon commented on src/logic/calculate.js
> +      if (obj.next) {
Never mind sir!